## **Checking accuracy for Breast Cancer Diagnosis Classifier with KNN, Logistic Regression, RF and SVM and comparing accuracy with and without Hyper-parameter Tuning and Feature Engineering**

In [1]:
#importing  libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
#reading the file
df = pd.read_csv(r'C:\Users\Priti\Desktop\corpnce_data_science\kaggle proj\breast_cancer_data.csv')
print(df.shape)
print(df.columns)
print(df.columns.size)


(569, 33)
Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')
33


In [3]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

      ...       texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0     ...               17.33           184.60      2019.0            0.1622   
1     ...               23.41           158.80      1956.0            0.1238   
2     ...               25.53           152.50      1709.0            0.1444   
3     ...               26.50            98.87       567.7            0.2098   
4     ...               16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.info() # no null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
id                         569 non-null int64
diagnosis                  569 non-null object
radius_mean                569 non-null float64
texture_mean               569 non-null float64
perimeter_mean             569 non-null float64
area_mean                  569 non-null float64
smoothness_mean            569 non-null float64
compactness_mean           569 non-null float64
concavity_mean             569 non-null float64
concave points_mean        569 non-null float64
symmetry_mean              569 non-null float64
fractal_dimension_mean     569 non-null float64
radius_se                  569 non-null float64
texture_se                 569 non-null float64
perimeter_se               569 non-null float64
area_se                    569 non-null float64
smoothness_se              569 non-null float64
compactness_se             569 non-null float64
concavity_se               569 non

In [5]:
df.describe()

id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean     ...       texture_worst  perimeter_worst  \
count     569.000000     ...          569.000000       569.000000   
mean        0.181162     ...           25.677223       107.261213   
std         0.027414     ...            6.146258        33.602542   
min         0.106000     ...           12.020000        50.410000   
25%         0.161900     ...           21.080000        84.110000   
50%         0.179200     ...           25.410000        97.660000   
75%         0.195700     ...           29.720000       125.400000   
max         0.304000     ...           49.540000       251.200000   

        area_worst  smoothness_worst  compactness_worst  concavity_worst  \
count   569.000000        569.000000         569.000000       569.000000   
mean    880.583128          0.132369           0.254265         0.272188   
std     569.356993          0.022832           0.157336         0.208624   
min     185.200000          0.071170           0.027290         0.000000   
25%     515.300000          0.116600           0.147200         0.114500   
50%     686.500000          0.131300           0.211900         0.226700   
75%    1084.000000          0.146000           0.339100         0.382900   
max    4254.000000          0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  \
count            569.000000      569.000000               569.000000   
mean               0.114606        0.290076                 0.083946   
std                0.065732        0.061867                 0.018061   
min                0.000000        0.156500                 0.055040   
25%                0.064930        0.250400                 0.071460   
50%                0.099930        0.282200                 0.080040   
75%                0.161400        0.317900                 0.092080   
max                0.291000        0.663800                 0.207500   

       Unnamed: 32  
count          0.0  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN  

[8 rows x 32 columns]

In [6]:
#deleting 2 columns which are not usefull
df.drop(['id','Unnamed: 32'],axis=1,inplace=True)

In [7]:
#counting diagnosis variable
df.diagnosis.value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [8]:
#diagnosis is the label data, convert it to numeric
#replacing M and B with 1 and 0 respectively
df.diagnosis.replace(('M','B'),(1,0),inplace=True)

In [9]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0          1        17.99         10.38          122.80     1001.0   
1          1        20.57         17.77          132.90     1326.0   
2          1        19.69         21.25          130.00     1203.0   
3          1        11.42         20.38           77.58      386.1   
4          1        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean           ...             radius_worst  texture_worst  \
0         0.2419           ...                    25.38          17.33   
1         0.1812           ...                    24.99          23.41   
2         0.2069           ...                    23.57          25.53   
3         0.2597           ...                    14.91          26.50   
4         0.1809           ...                    22.54          16.67   

   perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0           184.60      2019.0            0.1622             0.6656   
1           158.80      1956.0            0.1238             0.1866   
2           152.50      1709.0            0.1444             0.4245   
3            98.87       567.7            0.2098             0.8663   
4           152.20      1575.0            0.1374             0.2050   

   concavity_worst  concave points_worst  symmetry_worst  \
0           0.7119                0.2654          0.4601   
1           0.2416                0.1860          0.2750   
2           0.4504                0.2430          0.3613   
3           0.6869                0.2575          0.6638   
4           0.4000                0.1625          0.2364   

   fractal_dimension_worst  
0                  0.11890  
1                  0.08902  
2                  0.08758  
3                  0.17300  
4                  0.07678  

[5 rows x 31 columns]

**Creating a model with no hyper parameter tuning and no feature engineering**


In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
from sklearn.preprocessing import StandardScaler

In [11]:
#separating feature data and labels

X = df.iloc[:,1:]
y= df.diagnosis
print(X.shape)
print(y.shape)

(569, 30)
(569,)


In [12]:
#Splitting data into train and test
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.2,random_state=42)
print(X_train.shape)
print(X_test.shape)

(455, 30)
(114, 30)


**Logistic regression without hyperparameter tuning and feature engineering**

In [13]:

log = LogisticRegression()
log.fit(X_train,y_train)
pred_log = log.predict(X_test)
print('Accuracy score of logistic regression is : ', metrics.accuracy_score(pred_log,y_test),'\n')
print('confusion matrix:\n', metrics.confusion_matrix(pred_log,y_test))


Accuracy score of logistic regression is :  0.956140350877193 

confusion matrix:
 [[70  4]
 [ 1 39]]


**Random forest classifier without hyperparameter tuning and feature engineering**

In [14]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
pred_rf = rf.predict(X_test)
print('Accuracy score of logistic regression is : ', metrics.accuracy_score(pred_rf,y_test),'\n')
print('confusion matrix:\n', metrics.confusion_matrix(pred_rf,y_test))


Accuracy score of Random Forest is :  0.9649122807017544 

confusion matrix:
 [[70  3]
 [ 1 40]]


**SVM without hyperparameter tuning and feature engineering**

In [15]:
svm = SVC()
svm.fit(X_train,y_train)
pred_svm = svm.predict(X_test)
print('Accuracy score of logistic regression is : ', metrics.accuracy_score(pred_svm,y_test),'\n')
print('confusion matrix:\n', metrics.confusion_matrix(pred_svm,y_test))


Accuracy score of SVM is :  0.6228070175438597 

confusion matrix:
 [[71 43]
 [ 0  0]]


**KNN without hyperparameter tuning and feature engineering**

In [16]:
knn = KNeighborsClassifier()
knn.fit(X_train,y_train)
pred_knn = knn.predict(X_test)
print('Accuracy score of logistic regression is : ', metrics.accuracy_score(pred_knn,y_test),'\n')
print('confusion matrix:\n', metrics.confusion_matrix(pred_knn,y_test))


Accuracy score of KNN is :  0.956140350877193 

confusion matrix:
 [[71  5]
 [ 0 38]]


**Create model by tuning hyper parameter tuning and feature engineering**

In [17]:
#standerdising the data 
std = StandardScaler()
X_std = std.fit_transform(X)
X_std = pd.DataFrame(X_std)
X_std.describe()

0             1             2             3             4   \
count  5.690000e+02  5.690000e+02  5.690000e+02  5.690000e+02  5.690000e+02   
mean  -1.256562e-16  1.049736e-16 -1.272171e-16 -1.900452e-16  1.490704e-16   
std    1.000880e+00  1.000880e+00  1.000880e+00  1.000880e+00  1.000880e+00   
min   -2.029648e+00 -2.229249e+00 -1.984504e+00 -1.454443e+00 -3.112085e+00   
25%   -6.893853e-01 -7.259631e-01 -6.919555e-01 -6.671955e-01 -7.109628e-01   
50%   -2.150816e-01 -1.046362e-01 -2.359800e-01 -2.951869e-01 -3.489108e-02   
75%    4.693926e-01  5.841756e-01  4.996769e-01  3.635073e-01  6.361990e-01   
max    3.971288e+00  4.651889e+00  3.976130e+00  5.250529e+00  4.770911e+00   

                 5             6             7             8             9   \
count  5.690000e+02  5.690000e+02  5.690000e+02  5.690000e+02  5.690000e+02   
mean   2.544342e-16 -1.338511e-16 -8.429110e-17  2.081912e-16  5.408679e-16   
std    1.000880e+00  1.000880e+00  1.000880e+00  1.000880e+00  1.000880e+00   
min   -1.610136e+00 -1.114873e+00 -1.261820e+00 -2.744117e+00 -1.819865e+00   
25%   -7.470860e-01 -7.437479e-01 -7.379438e-01 -7.032397e-01 -7.226392e-01   
50%   -2.219405e-01 -3.422399e-01 -3.977212e-01 -7.162650e-02 -1.782793e-01   
75%    4.938569e-01  5.260619e-01  6.469351e-01  5.307792e-01  4.709834e-01   
max    4.568425e+00  4.243589e+00  3.927930e+00  4.484751e+00  4.910919e+00   

           ...                 20            21            22            23  \
count      ...       5.690000e+02  5.690000e+02  5.690000e+02  5.690000e+02   
mean       ...      -7.988142e-16 -1.834112e-17 -4.015534e-16 -2.848727e-17   
std        ...       1.000880e+00  1.000880e+00  1.000880e+00  1.000880e+00   
min        ...      -1.726901e+00 -2.223994e+00 -1.693361e+00 -1.222423e+00   
25%        ...      -6.749213e-01 -7.486293e-01 -6.895783e-01 -6.421359e-01   
50%        ...      -2.690395e-01 -4.351564e-02 -2.859802e-01 -3.411812e-01   
75%        ...       5.220158e-01  6.583411e-01  5.402790e-01  3.575891e-01   
max        ...       4.094189e+00  3.885905e+00  4.287337e+00  5.930172e+00   

                 24            25            26            27            28  \
count  5.690000e+02  5.690000e+02  5.690000e+02  5.690000e+02  5.690000e+02   
mean  -2.189227e-16 -2.579464e-16  1.143393e-16  2.829215e-16  1.670212e-16   
std    1.000880e+00  1.000880e+00  1.000880e+00  1.000880e+00  1.000880e+00   
min   -2.682695e+00 -1.443878e+00 -1.305831e+00 -1.745063e+00 -2.160960e+00   
25%   -6.912304e-01 -6.810833e-01 -7.565142e-01 -7.563999e-01 -6.418637e-01   
50%   -4.684277e-02 -2.695009e-01 -2.182321e-01 -2.234689e-01 -1.274095e-01   
75%    5.975448e-01  5.396688e-01  5.311411e-01  7.125100e-01  4.501382e-01   
max    3.955374e+00  5.112877e+00  4.700669e+00  2.685877e+00  6.046041e+00   

                 29  
count  5.690000e+02  
mean   2.321908e-16  
std    1.000880e+00  
min   -1.601839e+00  
25%   -6.919118e-01  
50%   -2.164441e-01  
75%    4.507624e-01  
max    6.846856e+00  

[8 rows x 30 columns]

In [18]:
X_std_train,X_std_test,y_train,y_test = train_test_split(X_std,y,test_size=.2,random_state=42)
print(X_std_train.shape)
print(X_std_test.shape)


(455, 30)
(114, 30)


**Logistic Regression with hyper parameter tuning and feature engineering**


In [19]:

log = LogisticRegression()
param_grid = {
    'C': [.01,.1,1]
}

grid = GridSearchCV(log, param_grid, cv = 7)
print(grid.fit(X_std_train, y_train))


GridSearchCV(cv=7, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [0.01, 0.1, 1]}, pre_dispatch='2*n_jobs',
       refit=True, return_train_score='warn', scoring=None, verbose=0)


In [20]:
print(grid.best_params_)

{'C': 0.1}


In [21]:
log = LogisticRegression(C=0.1)
log.fit(X_std_train,y_train)
pred_log = log.predict(X_std_test)
print('Accuracy score of logistic regression is : ', metrics.accuracy_score(pred_log,y_test),'\n')
print('confusion matrix:\n', metrics.confusion_matrix(pred_log,y_test))


Accuracy score of logistic regression is :  0.9912280701754386 

confusion matrix:
 [[71  1]
 [ 0 42]]


**Random Forest with hyper parameter tuning and feature engineering**

In [22]:
rf = RandomForestClassifier(random_state=42, n_jobs=-1)
param_grid ={'criterion':['gini','entropy'],
          'n_estimators':[10,30,50],
           'max_depth' :[2,3,4],
             'n_jobs':[-1]
          }

grid = GridSearchCV(rf, param_grid, cv = 7)
print(grid.fit(X_std_train, y_train))


GridSearchCV(cv=7, error_score='raise',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=-1,
            oob_score=False, random_state=42, verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'criterion': ['gini', 'entropy'], 'n_estimators': [10, 30, 50], 'max_depth': [2, 3, 4], 'n_jobs': [-1]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)


In [23]:
grid.best_params_

{'criterion': 'entropy', 'max_depth': 4, 'n_estimators': 10, 'n_jobs': -1}

In [24]:
rf = RandomForestClassifier(criterion='entropy',max_depth=4,n_estimators=10 ,random_state=42,n_jobs=-1)
rf.fit(X_std_train,y_train)
pred_rf = rf.predict(X_std_test)
print('Accuracy score of logistic regression is : ', metrics.accuracy_score(pred_rf,y_test),'\n')
print('confusion matrix:\n', metrics.confusion_matrix(pred_rf,y_test))


Accuracy score of Random Forest is :  0.956140350877193 

confusion matrix:
 [[70  4]
 [ 1 39]]


**SVM with hyper parameter tuning and featire engineering**

In [25]:
svm = SVC()
param_grid ={'C':[.01,.1,1,10],
             'kernel':['linear','rbf','poly']
          }

grid = GridSearchCV(svm, param_grid, cv = 7)
print(grid.fit(X_std_train, y_train))

GridSearchCV(cv=7, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [0.01, 0.1, 1, 10], 'kernel': ['linear', 'rbf', 'poly']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)


In [26]:
grid.best_params_

{'C': 0.1, 'kernel': 'linear'}

In [27]:
svm = SVC(C=.1,kernel='linear')
svm.fit(X_std_train,y_train)
pred_svm = svm.predict(X_std_test)
print('Accuracy score of logistic regression is : ', metrics.accuracy_score(pred_svm,y_test),'\n')
print('confusion matrix:\n', metrics.confusion_matrix(pred_svm,y_test))


Accuracy score of SVM is :  0.9824561403508771 

confusion matrix:
 [[71  2]
 [ 0 41]]


**KNN with hyper parameter tuning and feature engineering**

In [28]:
knn = KNeighborsClassifier(n_jobs=-1)
param_grid ={'n_neighbors':[5,6,7,8,9,10],
             'n_jobs':[-1]
          }

grid = GridSearchCV(knn, param_grid, cv = 7)
print(grid.fit(X_std_train, y_train))

GridSearchCV(cv=7, error_score='raise',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'n_neighbors': [5, 6, 7, 8, 9, 10], 'n_jobs': [-1]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)


In [29]:
grid.best_params_

{'n_jobs': -1, 'n_neighbors': 9}

In [30]:
knn = KNeighborsClassifier(n_neighbors=9)
knn.fit(X_std_train,y_train)
pred_knn = knn.predict(X_std_test)
print('Accuracy score of logistic regression is : ', metrics.accuracy_score(pred_knn,y_test),'\n')
print('confusion matrix:\n', metrics.confusion_matrix(pred_knn,y_test))


Accuracy score of KNN is :  0.9649122807017544 

confusion matrix:
 [[69  2]
 [ 2 41]]


**Results:**

**With No Hyper Parameter Tuning & Standardization **                                

Logistic Regression test accuracy:                95.61                                        

Random Forest test accuracy:96.49                                        

SVM test accuracy: 62.28                                        

KNN test accuracy: 95.61                                        

**With Hyper Parameter Tuning & Standardization **
 
 Logistic Regression test accuracy : 99.12
 
 Random Forest test accuracy : 95.61
 
 SVM test accuracy : 98.24
 
 KNN test accuracy : 96.49


**Conculsion**

We could see a drastic change in SVM after hyper parameter tuning and after standardization

In Regression we could see a good performance(almost 4%) after hyperparameter tuning

Slight changes are seen in  KNN

Default hyper parameter set of Random Forest looks better